---
abstract: 'Module collection to parse Matroska files.'
author:
  - 'Kovensky <diogomfranco@gmail.com>'
build_requires:
  Data::Dumper: 0
  File::Spec::Functions: 0
  FindBin: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parse-Matroska
requires:
  Carp: 0
  Encode: 0
  Exporter: 0
  IO::File: 0
  IO::Handle: 0
  List::Util: 0
  Scalar::Util: 0
  bigint: 0
  bigrat: 0
  constant: 0
  perl: 5.008
  strict: 0
  warnings: 0
version: 0.001
